architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

def commonGeneratedResources = project(':common').file("src/generated/resources")
def commonSharedResources = project(':common').file("src/main/resources")

sourceSets {
    main {
        resources {
            srcDir commonSharedResources
            srcDir commonGeneratedResources
        }
    }
}

fabricApi {
    configureDataGeneration() {
        client = true
        outputDirectory = commonGeneratedResources
    }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    implementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }

    implementation("maven.modrinth:forge-config-api-port:RXbL43Lt")
    api 'com.electronwill.night-config:core:3.8.1'
    api 'com.electronwill.night-config:toml:3.8.1'

    //Optional
    implementation("maven.modrinth:trinkets-updated:CFk62USu")
    implementation("maven.modrinth:modmenu:jvjwXH6l")

    //JEI
    implementation("maven.modrinth:jei:IfSmQWNL")
}

processResources {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neoforge_version       : neoforge_version,
            neoforge_version_range : neoforge_version_range,
            loader_version_range   : loader_version_range,
            mod_issue_tracker      : mod_issue_tracker,
            mod_source             : mod_source,
            mod_url                : mod_url,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_display_name       : mod_display_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            fabric_loader_dep      : fabric_loader_dep,
            fabric_api_dep         : fabric_api_dep,
            minecraft_dep          : minecraft_dep,
            java_dep               : java_dep,
            forgeconfigapiport_dep : forgeconfigapiport_dep
    ]
    inputs.properties replaceProperties

    filesMatching('fabric.mod.json') {
        expand replaceProperties
    }
}

jar {
    archiveClassifier = "raw"
}

java {
    withSourcesJar()
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    from rootProject.file("LICENSE.md")
}