# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
enabled_platforms=fabric,neoforge
mod_id=cloudboots
mod_version=3.0.3
mod_group_id=com.tiviacz.cloudboots
mod_name=CloudBoots
mod_display_name=Cloud Boots
mod_license=All Rights Reserved
mod_authors=Tiviacz1337
mod_description=Make your journeys through the Minecraft world more enjoyable with the Cloud Boots!
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/cloud-boots
mod_issue_tracker_url=https://github.com/Tiviacz1337/Cloud-Boots/issues

# Minecraft Version Information
minecraft_version=1.21.5
minecraft_version_range_neoforge=[1.21.5, 1.22)
minecraft_version_range_fabric=~1.21.5

# Neo Version Information
neoforge_version=21.5.96
neoforge_version_range=[21.5.0,)
loader_version_range=[2,)

# Fabric Version Information
fabric_loader_version = 0.18.4
fabric_api_version = 0.128.2+1.21.5