# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

# Mod properties
enabled_platforms=fabric,neoforge
mod_id=cloudboots
mod_version=3.0.3
mod_group_id=com.tiviacz.cloudboots
mod_name=CloudBoots
mod_display_name=Cloud Boots
mod_license=All Rights Reserved
mod_authors=Tiviacz1337
mod_description=Make your journeys through the Minecraft world more enjoyable with the Cloud Boots!
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/cloud-boots
mod_issue_tracker_url=https://github.com/Tiviacz1337/Cloud-Boots/issues

# Minecraft Version Information
minecraft_version=26.3
minecraft_version_range_neoforge=[26.3,)
minecraft_version_range_fabric=~26.3

# Neo Version Information
neoforge_version=26.3.0.41-beta
neoforge_version_range=[26.3.0.1-beta,)

# Fabric Version Information
fabric_loader_version = 0.19.5
fabric_api_version = 0.160.7+26.3