# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version=3.0.2
maven_group=com.tiviacz
archives_name=cloud-boots
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=1.21.8
minecraft_version_range=[1.21.8, 1.22)

# Fabric
fabric_loader_version=0.18.4
fabric_api_version=0.136.1+1.21.8

# NeoForge
neoforge_version=21.8.52
neoforge_version_range=[21.8.0,)
loader_version_range=[2,)

# Mod Version Information
mod_name=CloudBoots
mod_display_name=Cloud Boots
mod_id=cloudboots

mod_license=All Rights Reserved
mod_authors=Tiviacz1337
mod_description=Make your journeys through the Minecraft world more enjoyable with the Cloud Boots!

mod_issue_tracker=https://github.com/Tiviacz1337/CloudBoots/issues
mod_source=https://github.com/Tiviacz1337/CloudBoots
mod_url=https://www.curseforge.com/minecraft/mc-mods/cloud-boots-mod

# Version specific properties
parchment_version=2025.09.14
forge_config_api_port_version=YbUUjWdw
modmenu_version=kiOz1Uxm
curios_version=UW476H0a
trinkets_version=1MdtHaxo
jei_version_neo=ru8HioLg
jei_version_fabric=TvqzuFwN //Need Update

# Fabric Dependencies
fabric_loader_dep=>=0.15.11
fabric_api_dep=>=0.119.5
minecraft_dep=~1.21.8
java_dep=>=21
forgeconfigapiport_dep=*