plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

def generatedResources = file("../common/src/generated/resources")
def commonSharedResources = project(':common').file("src/main/resources")

sourceSets {
    main {
        resources {
            srcDir commonSharedResources
            srcDir generatedResources
        }
    }
}

loom {
    forge {
        mixinConfig "cloudboots.mixins.json"
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')

    modImplementation("maven.modrinth:forge-config-screens:$rootProject.forge_config_screens_version_forge")

    //Optional
    modImplementation("maven.modrinth:curios:$rootProject.curios_version")
    modImplementation("maven.modrinth:jei:$rootProject.jei_version_forge")
}

processResources {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_loader_version   : forge_loader_version,
            mod_issue_tracker      : mod_issue_tracker,
            mod_source             : mod_source,
            mod_url                : mod_url,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_display_name       : mod_display_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            fabric_loader_dep      : fabric_loader_dep,
            fabric_api_dep         : fabric_api_dep,
            minecraft_dep          : minecraft_dep,
            java_dep               : java_dep,
            forgeconfigapiport_dep : forgeconfigapiport_dep
    ]
    inputs.properties replaceProperties

    filesMatching('META-INF/mods.toml') {
        expand replaceProperties
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
    destinationDirectory.set(layout.buildDirectory.dir("intermediate-libs"))
}

remapJar {
    inputFile.set shadowJar.archiveFile
    //atAccessWideners.add("${rootProject.mod_id}.accesswidener")
}