architectury {
    common rootProject.enabled_platforms.split(',')
}

configurations {
    shadowCommon
}

dependencies {
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    implementation("maven.modrinth:forge-config-api-port:c1wkPZ5n")
}

jar {
    archiveClassifier = "raw"
}

java {
    withSourcesJar()
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    from rootProject.file("LICENSE")
}