modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL="https://github.com/Tiviacz1337/CloudBoots/issues"
license = "All Rights Reserved"

[[mods]]
modId = "cloudboots"
version = "${version}"
displayName="Cloud Boots"
updateJSONURL="https://gist.githubusercontent.com/Tiviacz1337/3f4df725e9107ae6093e07c498515d01/raw"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cloud-boots-mod"
authors="Tiviacz1337"
description='Make your journeys through the Minecraft world more enjoyable with the Cloud Boots!'

[[dependencies.cloudboots]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cloudboots]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"
