plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

def generatedResources = file("../common/src/generated/resources")
def commonSharedResources = project(':common').file("src/main/resources")

sourceSets {
    main {
        resources {
            srcDir commonSharedResources
            srcDir generatedResources
        }
    }
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')

    //Optional
    modImplementation("maven.modrinth:curios:UW476H0a")
    modImplementation("maven.modrinth:jei:ru8HioLg")
}

processResources {
    var replaceProperties = [
            minecraft_version                   : minecraft_version,
            minecraft_version_range_neoforge    : minecraft_version_range_neoforge,
            loader_version_range                : loader_version_range,
            mod_id                              : mod_id,
            mod_name                            : mod_name,
            mod_display_name                    : mod_display_name,
            mod_license                         : mod_license,
            mod_version                         : mod_version,
            mod_authors                         : mod_authors,
            mod_description                     : mod_description,
            mod_display_url                     : mod_display_url,
            mod_issue_tracker_url               : mod_issue_tracker_url,
    ]
    inputs.properties replaceProperties

    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}

publishMods {
    displayName = "cloudboots-neoforge-$rootProject.minecraft_version-$rootProject.mod_version"
    type = STABLE

    file = remapJar.archiveFile

    def changelogFile = file('CHANGELOG.md')
    changelog = changelogFile.exists() ? changelogFile.text : 'CHANGELOG.md not found'

    modLoaders.add("neoforge")

    curseforge {
        projectId = "291246"
        version = rootProject.mod_version
        accessToken = providers.gradleProperty('CURSEFORGE_TOKEN')
        minecraftVersions.add(rootProject.minecraft_version)
        javaVersions.add(JavaVersion.VERSION_21)
        client = true
        server = true
    }

    modrinth {
        projectId = "hkztOJro"
        version = minecraft_version + "-" + mod_version
        accessToken = providers.gradleProperty('MODRINTH_TOKEN')
        minecraftVersions.add(rootProject.minecraft_version)
        environment = CLIENT_AND_SERVER
    }
}